#!/bin/sh

case "$ACTION" in
	issued | renewed)
		[ "$(uci -q get ikev2-manager.globals.configured)" = 1 ] || exit 0
		[ "$(uci -q get ikev2-manager.server.enabled)" = 1 ] || exit 0
		/usr/libexec/ikev2-manager server-cert-sync
		;;
esac
