#!/bin/sh /etc/rc.common

START=96
STOP=4
USE_PROCD=1

start_service() {
	[ "$(uci -q get ikev2-manager.globals.configured)" = 1 ] ||
	[ "$(uci -q get ikev2-manager.client.enabled)" = 1 ] ||
	[ "$(uci -q get ikev2-manager.server.enabled)" = 1 ] ||
		return 0
	procd_open_instance
	procd_set_param command /usr/libexec/ikev2-health
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
